In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
columns = [
"duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent",
"hot","num_failed_logins","logged_in","num_compromised","root_shell","su_attempted","num_root",
"num_file_creations","num_shells","num_access_files","num_outbound_cmds","is_host_login",
"is_guest_login","count","srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate",
"same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
"dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
"dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
"dst_host_rerror_rate","dst_host_srv_rerror_rate","label","difficulty"
]

df_train = pd.read_csv('/content/KDDTrain+.txt',names = columns)
df_test = pd.read_csv('/content/KDDTest+.txt',names = columns)

In [ ]:
df_train

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125968,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune,20
125969,8,udp,private,SF,105,145,0,0,0,0,...,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal,21
125970,0,tcp,smtp,SF,2231,384,0,0,0,0,...,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal,18
125971,0,tcp,klogin,S0,0,0,0,0,0,0,...,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,20
125972,0,tcp,ftp_data,SF,151,0,0,0,0,0,...,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal,21

In [ ]:
df_test

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22539,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.72,0.06,0.01,0.01,0.01,0.0,0.00,0.00,normal,21
22540,0,tcp,http,SF,317,938,0,0,0,0,...,1.00,0.00,0.01,0.01,0.01,0.0,0.00,0.00,normal,21
22541,0,tcp,http,SF,54540,8314,0,0,0,2,...,1.00,0.00,0.00,0.00,0.00,0.0,0.07,0.07,back,15
22542,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal,21
22543,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.08,0.03,0.00,0.00,0.00,0.0,0.44,1.00,mscan,14

In [ ]:
df = pd.concat([df_train, df_test],axis =0)

In [ ]:
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22539,0,tcp,smtp,SF,794,333,0,0,0,0,...,0.72,0.06,0.01,0.01,0.01,0.00,0.00,0.00,normal,21
22540,0,tcp,http,SF,317,938,0,0,0,0,...,1.00,0.00,0.01,0.01,0.01,0.00,0.00,0.00,normal,21
22541,0,tcp,http,SF,54540,8314,0,0,0,2,...,1.00,0.00,0.00,0.00,0.00,0.00,0.07,0.07,back,15
22542,0,udp,domain_u,SF,42,42,0,0,0,0,...,0.99,0.01,0.00,0.00,0.00,0.00,0.00,0.00,normal,21
22543,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,0.08,0.03,0.00,0.00,0.00,0.00,0.44,1.00,mscan,14

# Preprocessing
what all i can make of this data is that we need to label encode this values we can individually select a few of the columns and encode them directly

Also we can do this that we can make a pipeline for easier compute. Here we will do both

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148517 entries, 0 to 22543
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     148517 non-null  int64
 1   protocol_type                148517 non-null  object
 2   service                      148517 non-null  object
 3   flag                         148517 non-null  object
 4   src_bytes                    148517 non-null  int64
 5   dst_bytes                    148517 non-null  int64
 6   land                         148517 non-null  int64
 7   wrong_fragment               148517 non-null  int64
 8   urgent                       148517 non-null  int64
 9   hot                          148517 non-null  int64
 10  num_failed_logins            148517 non-null  int64
 11  logged_in                    148517 non-null  int64
 12  num_compromised              148517 non-null  int64
 13  root_shell                   148517 non-null  int64
 14  su_attempted                 148517 non-null  int64
 15  num_root                     148517 non-null  int64
 16  num_file_creations           148517 non-null  int64
 17  num_shells                   148517 non-null  int64
 18  num_access_files             148517 non-null  int64
 19  num_outbound_cmds            148517 non-null  int64
 20  is_host_login                148517 non-null  int64
 21  is_guest_login               148517 non-null  int64
 22  count                        148517 non-null  int64
 23  srv_count                    148517 non-null  int64
 24  serror_rate                  148517 non-null  float64
 25  srv_serror_rate              148517 non-null  float64
 26  rerror_rate                  148517 non-null  float64
 27  srv_rerror_rate              148517 non-null  float64
 28  same_srv_rate                148517 non-null  float64
 29  diff_srv_rate                148517 non-null  float64
 30  srv_diff_host_rate           148517 non-null  float64
 31  dst_host_count               148517 non-null  int64
 32  dst_host_srv_count           148517 non-null  int64
 33  dst_host_same_srv_rate       148517 non-null  float64
 34  dst_host_diff_srv_rate       148517 non-null  float64
 35  dst_host_same_src_port_rate  148517 non-null  float64
 36  dst_host_srv_diff_host_rate  148517 non-null  float64
 37  dst_host_serror_rate         148517 non-null  float64
 38  dst_host_srv_serror_rate     148517 non-null  float64
 39  dst_host_rerror_rate         148517 non-null  float64
 40  dst_host_srv_rerror_rate     148517 non-null  float64
 41  label                        148517 non-null  object
 42  difficulty                   148517 non-null  int64
dtypes: float64(15), int64(24), object(4)
memory usage: 49.9+ MB

In [ ]:
df['label'].unique()

array(['normal', 'neptune', 'warezclient', 'ipsweep', 'portsweep',
       'teardrop', 'nmap', 'satan', 'smurf', 'pod', 'back',
       'guess_passwd', 'ftp_write', 'multihop', 'rootkit',
       'buffer_overflow', 'imap', 'warezmaster', 'phf', 'land',
       'loadmodule', 'spy', 'perl', 'saint', 'mscan', 'apache2',
       'snmpgetattack', 'processtable', 'httptunnel', 'ps', 'snmpguess',
       'mailbomb', 'named', 'sendmail', 'xterm', 'worm', 'xlock',
       'xsnoop', 'sqlattack', 'udpstorm'], dtype=object)

In [ ]:
df['flag'].unique()

array(['SF', 'S0', 'REJ', 'RSTR', 'SH', 'RSTO', 'S1', 'RSTOS0', 'S3',
       'S2', 'OTH'], dtype=object)

## we will use
* standard scalar for numerical values and
* LabelEncoder for categorical or object values

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

numerical_columns = df.drop(columns = ['protocol_type','service','flag','label'], axis =1)
categorical_columns = df[['protocol_type','service','flag','label']]
numerical_columns.shape, categorical_columns.shape

((148517, 39), (148517, 4))

In [35]:
scalar = StandardScaler()
X1 = scalar.fit_transform(numerical_columns)
X1 = pd.DataFrame(X1)
X1.columns = numerical_columns.columns
X1

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,difficulty
0,-0.112481,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.849240,-0.813554,-0.278736,0.077981,-0.280650,-0.597720,-0.584813,-0.267151,-0.406815,0.263353
1,-0.112481,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-1.065006,-1.192968,2.657874,2.378421,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,-1.561632
2,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.840250,-0.969783,-0.175697,-0.472829,-0.280650,1.736012,1.742295,-0.422074,-0.406815,-0.101644
3,-0.112481,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,1.218511,1.038878,-0.433294,-0.375627,0.086408,-0.527708,-0.561542,-0.422074,-0.376989,0.628350
4,-0.112481,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,1.218511,1.038878,-0.433294,-0.472829,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148512,-0.112481,-0.007290,-0.004524,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,0.193625,0.413961,-0.124178,-0.440428,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350
148513,-0.112481,-0.007378,-0.004361,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,1.218511,1.038878,-0.433294,-0.440428,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350
148514,-0.112481,0.002646,-0.002369,-0.01468,-0.085488,-0.010403,0.899396,-0.059832,1.217658,0.033509,...,1.218511,1.038878,-0.433294,-0.472829,-0.280650,-0.597720,-0.584813,-0.205182,-0.198035,-1.561632
148515,-0.112481,-0.007429,-0.004603,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,1.191540,1.016560,-0.381775,-0.472829,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350
148516,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.885201,-1.014420,-0.278736,-0.472829,-0.280650,-0.597720,-0.584813,0.941252,2.575756,-1.926630

In [36]:
encoder = LabelEncoder()
X2 = categorical_columns.apply(encoder.fit_transform)
print(X2)

       protocol_type  service  flag  label
0                  1       20     9     16
1                  2       44     9     16
2                  1       49     5     14
3                  1       24     9     16
4                  1       24     9     16
...              ...      ...   ...    ...
22539              1       54     9     16
22540              1       24     9     16
22541              1       24     9      1
22542              2       12     9     16
22543              1       57     1     11

[148517 rows x 4 columns]

In [37]:
data = pd.concat([X1, X2.reset_index(drop=True)], axis=1)
data.columns = data.columns.astype(str)

In [38]:
data.shape

(148517, 43)

In [39]:
data

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,difficulty,protocol_type,service,flag,label
0,-0.112481,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.267151,-0.406815,0.263353,1,20,9,16
1,-0.112481,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,-1.561632,2,44,9,16
2,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,1.736012,1.742295,-0.422074,-0.406815,-0.101644,1,49,5,14
3,-0.112481,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,0.086408,-0.527708,-0.561542,-0.422074,-0.376989,0.628350,1,24,9,16
4,-0.112481,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350,1,24,9,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148512,-0.112481,-0.007290,-0.004524,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350,1,54,9,16
148513,-0.112481,-0.007378,-0.004361,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350,1,24,9,16
148514,-0.112481,0.002646,-0.002369,-0.01468,-0.085488,-0.010403,0.899396,-0.059832,1.217658,0.033509,...,-0.280650,-0.597720,-0.584813,-0.205182,-0.198035,-1.561632,1,24,9,1
148515,-0.112481,-0.007429,-0.004603,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350,2,12,9,16
148516,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,0.941252,2.575756,-1.926630,1,57,1,11

In [40]:
data.isnull().sum()

duration                       0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
difficulty                     0
protocol_type                  0
service                        0
flag                           0
label                          0
dtype: int64

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148517 entries, 0 to 148516
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     148517 non-null  float64
 1   src_bytes                    148517 non-null  float64
 2   dst_bytes                    148517 non-null  float64
 3   land                         148517 non-null  float64
 4   wrong_fragment               148517 non-null  float64
 5   urgent                       148517 non-null  float64
 6   hot                          148517 non-null  float64
 7   num_failed_logins            148517 non-null  float64
 8   logged_in                    148517 non-null  float64
 9   num_compromised              148517 non-null  float64
 10  root_shell                   148517 non-null  float64
 11  su_attempted                 148517 non-null  float64
 12  num_root                     148517 non-null  float64
 13  num_file_creations           148517 non-null  float64
 14  num_shells                   148517 non-null  float64
 15  num_access_files             148517 non-null  float64
 16  num_outbound_cmds            148517 non-null  float64
 17  is_host_login                148517 non-null  float64
 18  is_guest_login               148517 non-null  float64
 19  count                        148517 non-null  float64
 20  srv_count                    148517 non-null  float64
 21  serror_rate                  148517 non-null  float64
 22  srv_serror_rate              148517 non-null  float64
 23  rerror_rate                  148517 non-null  float64
 24  srv_rerror_rate              148517 non-null  float64
 25  same_srv_rate                148517 non-null  float64
 26  diff_srv_rate                148517 non-null  float64
 27  srv_diff_host_rate           148517 non-null  float64
 28  dst_host_count               148517 non-null  float64
 29  dst_host_srv_count           148517 non-null  float64
 30  dst_host_same_srv_rate       148517 non-null  float64
 31  dst_host_diff_srv_rate       148517 non-null  float64
 32  dst_host_same_src_port_rate  148517 non-null  float64
 33  dst_host_srv_diff_host_rate  148517 non-null  float64
 34  dst_host_serror_rate         148517 non-null  float64
 35  dst_host_srv_serror_rate     148517 non-null  float64
 36  dst_host_rerror_rate         148517 non-null  float64
 37  dst_host_srv_rerror_rate     148517 non-null  float64
 38  difficulty                   148517 non-null  float64
 39  protocol_type                148517 non-null  int64
 40  service                      148517 non-null  int64
 41  flag                         148517 non-null  int64
 42  label                        148517 non-null  int64
dtypes: float64(39), int64(4)
memory usage: 48.7 MB

see a issue can be that from the result we obtained from standard scalar could resulting in a very out of way result
A solution can be use the data again in StandardScaler

## as we dont have classes we resort to unsupervised learning

In [42]:
scalar2 = StandardScaler()
X = scalar2.fit_transform(data)
X = pd.DataFrame(X)
X.columns = data.columns
X

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,difficulty,protocol_type,service,flag,label
0,-0.112481,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.267151,-0.406815,0.263353,-0.132017,-0.719829,0.733734,0.048224
1,-0.112481,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,-1.561632,2.235956,0.753338,0.733734,0.048224
2,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,1.736012,1.742295,-0.422074,-0.406815,-0.101644,-0.132017,1.060247,-0.707737,-0.394674
3,-0.112481,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,0.086408,-0.527708,-0.561542,-0.422074,-0.376989,0.628350,-0.132017,-0.474301,0.733734,0.048224
4,-0.112481,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350,-0.132017,-0.474301,0.733734,0.048224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148512,-0.112481,-0.007290,-0.004524,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350,-0.132017,1.367157,0.733734,0.048224
148513,-0.112481,-0.007378,-0.004361,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,1.217658,-0.011473,...,-0.188885,-0.574382,-0.584813,-0.422074,-0.406815,0.628350,-0.132017,-0.474301,0.733734,0.048224
148514,-0.112481,0.002646,-0.002369,-0.01468,-0.085488,-0.010403,0.899396,-0.059832,1.217658,0.033509,...,-0.280650,-0.597720,-0.584813,-0.205182,-0.198035,-1.561632,-0.132017,-0.474301,0.733734,-3.273512
148515,-0.112481,-0.007429,-0.004603,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,-0.422074,-0.406815,0.628350,2.235956,-1.210884,0.733734,0.048224
148516,-0.112481,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,-0.059832,-0.821249,-0.011473,...,-0.280650,-0.597720,-0.584813,0.941252,2.575756,-1.926630,-0.132017,1.551303,-2.149209,-1.059021

In [44]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148517 entries, 0 to 148516
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     148517 non-null  float64
 1   src_bytes                    148517 non-null  float64
 2   dst_bytes                    148517 non-null  float64
 3   land                         148517 non-null  float64
 4   wrong_fragment               148517 non-null  float64
 5   urgent                       148517 non-null  float64
 6   hot                          148517 non-null  float64
 7   num_failed_logins            148517 non-null  float64
 8   logged_in                    148517 non-null  float64
 9   num_compromised              148517 non-null  float64
 10  root_shell                   148517 non-null  float64
 11  su_attempted                 148517 non-null  float64
 12  num_root                     148517 non-null  float64
 13  num_file_creations           148517 non-null  float64
 14  num_shells                   148517 non-null  float64
 15  num_access_files             148517 non-null  float64
 16  num_outbound_cmds            148517 non-null  float64
 17  is_host_login                148517 non-null  float64
 18  is_guest_login               148517 non-null  float64
 19  count                        148517 non-null  float64
 20  srv_count                    148517 non-null  float64
 21  serror_rate                  148517 non-null  float64
 22  srv_serror_rate              148517 non-null  float64
 23  rerror_rate                  148517 non-null  float64
 24  srv_rerror_rate              148517 non-null  float64
 25  same_srv_rate                148517 non-null  float64
 26  diff_srv_rate                148517 non-null  float64
 27  srv_diff_host_rate           148517 non-null  float64
 28  dst_host_count               148517 non-null  float64
 29  dst_host_srv_count           148517 non-null  float64
 30  dst_host_same_srv_rate       148517 non-null  float64
 31  dst_host_diff_srv_rate       148517 non-null  float64
 32  dst_host_same_src_port_rate  148517 non-null  float64
 33  dst_host_srv_diff_host_rate  148517 non-null  float64
 34  dst_host_serror_rate         148517 non-null  float64
 35  dst_host_srv_serror_rate     148517 non-null  float64
 36  dst_host_rerror_rate         148517 non-null  float64
 37  dst_host_srv_rerror_rate     148517 non-null  float64
 38  difficulty                   148517 non-null  float64
 39  protocol_type                148517 non-null  float64
 40  service                      148517 non-null  float64
 41  flag                         148517 non-null  float64
 42  label                        148517 non-null  float64
dtypes: float64(43)
memory usage: 48.7 MB

In [45]:
from sklearn.ensemble import IsolationForest

forest = IsolationForest(n_estimators=100, contamination=0.01, random_state=42)
y_hat = forest.fit_predict(X)

In [46]:
y_hat

array([1, 1, 1, ..., 1, 1, 1])

In [50]:
X['class'] = pd.DataFrame(y_hat)

In [51]:
X.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised',
       'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
       'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'difficulty', 'protocol_type', 'service',
       'flag', 'label', 'class'],
      dtype='object')

In [52]:
X['class'].unique()

array([ 1, -1])

In [54]:
#the result yields 1 and -1, and we can process it all, with what all algo we want